### ISSUE TITLE
Indication - Substances

### ISSUE THREAD

**Issue by curki** [epha/download#12]
@Tony: Bitte Céline und Claudio die Substanzen ATC-gruppiert zuteilen, nicht zwischen den Gruppen hin und her springen. zB wenn jemand Omeprazol zugeteilt bekommt, bei A02BC Protonenpumpenhemmer bleiben, bis diese abgearbeitet sind. Die ATC-Gruppe (zB Protonenpumpenhemmer) wird dann von nur einer Person bearbeitet, nicht auf Céline UND Claudio aufteilen.

**Comment by aspergatus** [comment]
@curki Bei der Erstellung der Dateien wurde leider Information über ATC-Gruppe nicht berücksichtigt. Es wurde nur nach einmaliger Fachinfo-Text gesucht, sortiert nach Zulassungsnummer. Daher ist es im Moment nicht möglich, die Substanzen nach ATC-Gruppe zu sortieren.
Ich werde aber versuchen, diese ATC-Information zu ergänzen und bei den späteren Zuteilungen berücksichtigen.

**Comment by aspergatus** [comment]
@Jonas74 Haben wir die Zuordnung von ATC und Zulassungsnummer irgendwo?
